DROP DATABASE IF EXISTS voting;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS roomMember;
DROP TABLE IF EXISTS vote;